### ISSUE TITLE
Protected strategy issue

### ISSUE THREAD

**Issue by kennuzzo** [antek-drzewiecki/wine_bouncer#20]
Hi, on a brand new rails 4.2.0 project with ruby 2.2.0, when i select the protected auth i get this: 

```
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/Giannuzzo/.rvm/gems/ruby-2.2.0@tlmri/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- wine_bouncer/auth_strategies/protected (LoadError)
```
Wine Bouncer initializer:

```ruby 
WineBouncer.configure do |config|
  config.auth_strategy = :protected

  config.define_resource_owner do
    User.find(doorkeeper_access_token.resource_owner_id) if doorkeeper_access_token
  end
end
```
I guess Protected is a protected keyword, works fine if i rename the class to anything else

**Comment by antek-drzewiecki** [comment]
This is probably because you are viewing the master manual. The protected strategy is just recently introduced.  But thanks for noting. I'll also add the ruby 2.2.0 version to the build server.

**Comment by antek-drzewiecki** [comment]
@kennuzzo a new version (0.2.2) is released, can you verify your issue has been solved?

**Comment by kennuzzo** [comment]
Sorry for the late response,  0.2.2 works like a charm :) 
keep up with the good work!
