### ISSUE TITLE
undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by kennuzzo** [antek-drzewiecki/wine_bouncer#24]
Hi There, im checking out the new DSL on 0.3.0, using the example given on the docs, but
when starting the server i get    ``` /gems/wine_bouncer-0.3.0/lib/wine_bouncer/extension.rb:12:in `oauth2': undefined method `[]=' for nil:NilClass (NoMethodError) ```

Here is the code :
``` ruby

 module API
 class MyAwesomeAPI < Grape::API
    desc 'protected method with required public scope'
    oauth2 'public'
    get '/protected' do
       { hello: 'world' }
    end

    oauth2 'public'
    get '/with_no_description' do
       { hello: 'undescribed world' }
    end

    desc 'Unprotected method'
    get '/unprotected' do
      { hello: 'unprotected world' }
    end

    desc 'This method needs the public or private scope.'
    oauth2 'public', 'write'
    get '/method' do
      { hello: 'public or private user.' }
    end

    desc 'This method uses Doorkeepers default scopes.'
    oauth2
    get '/protected_with_default_scope' do
       { hello: 'protected unscoped world' }
    end
 end
end

```

```ruby
module API
 class Base < Grape::API
    default_format :json
    format :json
    use ::WineBouncer::OAuth2
    mount ::MyAwesomeAPI
 end

end

```
When i comment all the oauth2 except for one, then it doesnt throw an error.

Also i might have misunderstood the usage, but in a protected strategy this will result in an unauthorized access :

```ruby
desc 'Unprotected method'
    oauth2 false
    get '/unprotected' do
      { hello: 'unprotected world' }
    end
```

Anyway thank you for the amazing work, i really like the new dsl :)

**Comment by kennuzzo** [comment]
i just got my Ah! moment, 
the protected strategy works :
 
```ruby
desc 'Unprotected method',
    oauth2: false
    get '/unprotected' do
      { hello: 'unprotected world' }
    end
```

**Comment by ddoolin** [comment]
Did the above code actually work for you? I noticed that having ```oauth2: false``` in the line above was throwing syntax errors and ```oauth2 false``` (note the lack of colon) just wasn't working to deauthorize endpoints using the protected strategy.

WineBouncer is checking the endpoint's route options to see if it's authorized, which would read something like this:

```post '', rabl: 'users/user', oauth2: false do```

That still doesn't work due to an error but I've made a PR in the meantime to address it.

**Comment by kennuzzo** [comment]
@ddoolin Yes sorry i meant ```auth: false```, while ```oauth2: false``` was not working

**Comment by calfzhou** [comment]
+1
`get :xxx, auth: false do` works for me!

**Comment by antek-drzewiecki** [comment]
oauth2 false
get :xxx
Should work on #27. @calfzhou @kennuzzo  care to verify?

**Comment by calfzhou** [comment]
it works, thank you :+1:

**Comment by antek-drzewiecki** [comment]
I'll release right away when I'm home. :)

**Comment by calfzhou** [comment]
@antek-drzewiecki, there is one more problem, `oauth2 false` now can make an endpoint public, but in the generated swagger doc, it shows that the endpoint requires an OAuth 2.0 with scope `false`:

![image](https://cloud.githubusercontent.com/assets/3761553/6499866/498ece86-c33d-11e4-8f47-1f2d1a06f72d.png)

**Comment by calfzhou** [comment]
similar issue when set `oauth2 nil`, will add a scope `null` to swagger doc.

![image](https://cloud.githubusercontent.com/assets/3761553/6499908/ecd34db0-c33d-11e4-91cf-370d9564549c.png)

**Comment by antek-drzewiecki** [comment]
Using default scopes on the swagger strategy was never an intention. Ill create a pull request where default scopes can be used by setting `oauth2 nil`. 

If you want a public endpoint with swagger, don't append the `oauth2` method for that case.
