### ISSUE TITLE
Oauth scopes end up in 'scope' property instead of 'scopes' property

### ISSUE THREAD

**Issue by guidoprincess** [antek-drzewiecki/wine_bouncer#26]
If I lock an endpoint down using a few scopes like:

```
 class MyAwesomeAPI < Grape::API
    oauth2 'foo', 'bar
    get '/with_no_description' do
       { hello: 'undescribed world' }
    end

 end
```

Then those scopes do not get picked up because for some reason, they end up put into the api_context.options[:route_options][:auth] hash under the key [:scope], not the key [:scopes].  Therefore, the has_auth_scopes? method in WineBouncer::AuthStrategies::Default always returns false (once again since no scopes are in [:scopes], everything is in [:scope], and all endpoints end up being locked down with only the default scope. 

I believe the bug is only with the new release (with the new DSL, version 0.3.0), so reverting back to the old style auth: DSL (version 0.2.0) fixes the issue.

Thanks,
Greg

**Comment by calfzhou** [comment]
Facing the same problem. Only strategy swagger works well with scopes.

**Comment by calfzhou** [comment]
Temporarily fix it by monkey patching using
```ruby
module WineBouncer
  module AuthStrategies
    class Default
      def auth_scopes?
        endpoint_authorizations &&
          endpoint_authorizations.key?(:scope) && endpoint_authorizations[:scope].any?
      end

      alias_method :has_auth_scopes?, :auth_scopes?

      def auth_scopes
        endpoint_authorizations[:scope].map(&:to_sym)
      end
    end

    class Protected
      def auth_scopes?
        endpoint_authorizations &&
          endpoint_authorizations.key?(:scope) && endpoint_authorizations[:scope].any?
      end

      alias_method :has_auth_scopes?, :auth_scopes?

      def auth_scopes
        endpoint_authorizations[:scope].map(&:to_sym)
      end
    end
  end
end
```

**Comment by antek-drzewiecki** [comment]
Thank you, ill have a fix within 20 minutes :+1: 
There was no spec that handles custom scopes. So I added these.

**Comment by antek-drzewiecki** [comment]
Default scope should work without the monkeypatch. 
@guidoprincess, @calfzhou care to verify?

**Comment by calfzhou** [comment]
it works!

**Comment by guidoprincess** [comment]
Yep, its better.  Feel free to close this and thank you as always!

**Comment by antek-drzewiecki** [comment]
Thank you for reporting :)
