### ISSUE TITLE
Relaxing Doorkeeper dependency requirement?

### ISSUE THREAD

**Issue by nickcharlton** [antek-drzewiecki/wine_bouncer#28]
The dependency requirement on Doorkeeper is currently very strict:

```ruby
'doorkeeper', '>= 1.4', '<= 2.1.1'
```

As I write this, the current version is 2.1.3 which fixes a local security vulnerability (see [here](https://github.com/doorkeeper-gem/doorkeeper/issues/576)) where sensitive data is logged.

What do you think of relaxing the versioning to something like this?

```ruby
'doorkeeper', '>= 1.4', '<= 2.1'
```

This would give us changes all the way up until 2.2, where I'd expect any notable changes (and not just fixes) to happen. I'd be happy to open up a PR if so.

**Comment by antek-drzewiecki** [comment]
Good idea! If you can check Travis.yml now tests against the most recent doorkeeper version, I'm happy to accept!

**Comment by nickcharlton** [comment]
Would you prefer bumping the listed version or adding another?

```yaml
- rails=4.1.1 grape=0.11.0 doorkeeper=2.1.1
```

**Comment by antek-drzewiecki** [comment]
Bump :)

**Comment by antek-drzewiecki** [comment]
Thank you for your effort. Relaxing to a patch level seems proper way. Do you have any thoughts about limiting restrictions to Doorkeepers major versions?

**Comment by nickcharlton** [comment]
I think it's best to keep an eye on it and update it manually. I rely on [Gemnasium](https://gemnasium.com) for this (it's how I noticed the vulnerability).
