### ISSUE TITLE
is it possible to support multiple oauth2 protections to one endpoint?

### ISSUE THREAD

**Issue by calfzhou** [antek-drzewiecki/wine_bouncer#33]
Doorkeeper's scope checking only ensure that the client has at least one required scopes, e.g. `oauth2 :x, :y, :z` will success even if the client's scope contains only `:x`. I'd like to protect an endpoint with multiple required scopes, e.g. only a client with both `:x` and `:y` permission can access the endpoint, is it possible make wine_bouncer support syntax like this:
```ruby
oauth2 :x
oauth2 :y
get :resources_with_both_x_and_y_permissions do
  ...
end
```

**Comment by antek-drzewiecki** [comment]
`oauth :x, :y` 
should do the trick!

**Comment by calfzhou** [comment]
do you mean `oauth2 :x, :y`? it not ensure the client have both `:x` and `:y` permissions, since `doorkeeper_token.acceptable?(scopes)` only make sure the token includes *any* (at least one) required scope.

**Comment by calfzhou** [comment]
one access token can be assigned with any number of scopes. when client app requesting for a token, its `:scope` could be a space separated string for more than one scopes. And in doorkeeper model, AccessToken.scopes is an array too.

**Comment by antek-drzewiecki** [comment]
I believe this should be an responsibility of Doorkeeper how it should handle token scopes. Do you agree? I doubt this kind of logic should be implemented in wine_bouncer, since it is mostly intended to pass rules to doorkeeper. Any other doorkeeper user might also profit from this implementation. My suggestion is to open a ticket there.

**Comment by calfzhou** [comment]
yes agree with you. i already asked them for this behavior, haven't got response yet.

I just checked swagger spec, though there is no explicit declaration about this, it's owner said it might be a logical AND between required scopes.

**Comment by antek-drzewiecki** [comment]
Indeed, the swagger spec fail to mention the behavior.

**Comment by calfzhou** [comment]
it would be great to support multiple `oauth2` for one endpoint ~~

**Comment by calfzhou** [comment]
or maybe syntax like
```ruby
oauth2 do
  authorize! :x, :y
  authorize! :z
end
```

so only if the client have either `[:x, :z]` or `[:y, :z]` permissions can use this endpoint.
