### ISSUE TITLE
doorkeeper 2.2.1 support

### ISSUE THREAD

**Issue by catogonzalez** [antek-drzewiecki/wine_bouncer#43]
Following installation instructions and aware of requirements as described in the readme, ```bundle install``` produces:
```
Resolving dependencies...
Bundler could not find compatible versions for gem "doorkeeper":
  In Gemfile:
    wine_bouncer (>= 0) ruby depends on
      doorkeeper (~> 1.4.0) ruby

    doorkeeper (2.2.1)
```
Requirements say: "Doorkeeper > 1.4.0 and < 3"

Appreciate any guidance.

**Comment by antek-drzewiecki** [comment]
Thats the master you are currently looking at. Ill be releasing the 0.4 in the near future #44 .

**Comment by antek-drzewiecki** [comment]
0.4.0 is released
