### ISSUE TITLE
Support grape 0.13.0

### ISSUE THREAD

**Issue by gottfrois** [antek-drzewiecki/wine_bouncer#49]
Any reasons why grape is lock to  `< 0.13.0`?

**Comment by antek-drzewiecki** [comment]
The only reason is to ensure everyone has proper experience with WineBouncer and Grape. I aim at a gem that is tested before new versions are supported.  Touch 0.13 should be a minor change, I have seen small breaking changes before.

Feel free to make a pull request that adds test or support for Grape 0.13. I can start working on it tomorrow :)

**Comment by antek-drzewiecki** [comment]
grape_v13 is the branch. Waiting for the travis build to complete.

**Comment by gottfrois** [comment]
Great! Can't wait for this to be released as a new version :)

**Comment by antek-drzewiecki** [comment]
Gem has been released yesterdays. 
Was struggling with illness abroad, therefor the release was delayed.
