### ISSUE TITLE
Grape 0.14.0 support

### ISSUE THREAD

**Issue by synth** [antek-drzewiecki/wine_bouncer#55]
Grape has a number of fixes and enhancements in 0.14.0. Is there a reason wine_bouncer is locking grape to minor versions?

**Comment by synth** [comment]
https://github.com/antek-drzewiecki/wine_bouncer/pull/56

**Comment by antek-drzewiecki** [comment]
The reason what grape did not always semver. Some interfaces changes were made in minor versions. I am willing to release the minor lock, but then I can not guarantee it will work with the minor versions.

**Comment by synth** [comment]
Cool, cool, thx for merging, pr. Closing this issue :)

**Comment by antek-drzewiecki** [comment]
Thank you for submitting the request! :)
