### ISSUE TITLE
support grape 1.3.0

### ISSUE THREAD

**Issue by alexmamonchik** [antek-drzewiecki/wine_bouncer#80]
grape was [released](https://github.com/ruby-grape/grape/releases/tag/v1.3.0) 8 days ago, but I can't upgrade it because wine_bouncer locked to `grape (< 1.3, >= 0.10)`

**Comment by sdfreund10** [comment]
I recently ran into this problem too. 
`grape 1.2.x` is incompatible with `rack >2.0.8` (see this issue https://github.com/ruby-grape/grape/issues/1966). Grape is not specifying this dependency and instead released a 1.3 version with a fix. It seems like either wine_bouncer should be made compatible with `grape 1.3` or a `rack <2.0.8`.
I'm not really sure what the best solution is going forward 😕. For now, I'd recommend anyone using wine_bouncer to version lock rack

**Comment by antek-drzewiecki** [comment]
I've used a passive lock strategy, to ensure it is tested against the released versions. The side effect is that people cant upgrade that fast. I think we could release the locks .

**Comment by sarojkh** [comment]
@antek-drzewiecki Any reason this has not been released as a gem? 

Thanks for the hard work!

**Comment by jacek213** [comment]
Bump

**Comment by antek-drzewiecki** [comment]
Cleaning up and closing issue. Support had been added.
